# -*- coding: utf-8 -*-
# 자재불출집계표(dw_pu_input_140) 라이브 검증 — 마감기준, 2607
import sys, io, warnings
warnings.filterwarnings("ignore")
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
sys.path.insert(0, r"d:\피앤씨인더스트리\100_AI_AGENT\Projects\New_ERP")
import db_client, pyodbc, pandas as pd
def live(sql):
    cs=(f"DRIVER={{SQL Server}};SERVER={db_client.DB_SERVER},{db_client.DB_PORT};"
        f"DATABASE=PARTNER_ERP;UID={db_client.DB_USER};PWD={db_client.DB_PASSWORD}")
    cn=pyodbc.connect(cs, readonly=True)
    try: return pd.read_sql(sql, cn)
    finally: cn.close()

DW = r"""
WITH MAGAM (CUST_CODE, JUN_YYMM, JUN_MAGAM_DAY, MAGAM_DAY) AS (
  SELECT CUST_CODE
    ,format(dateadd(MONTH,-1,convert(date,'2607'+'01',12)),'yyMM') as jun_yymm
    ,ISNULL((SELECT TOP 1 MAGAM_DAY FROM CM_M_CUST_MAGAM WHERE CUST_CODE=A.CUST_CODE AND APPLY_YYMM<=format(dateadd(MONTH,-1,convert(date,'2607'+'01',12)),'yyMM') ORDER BY APPLY_YYMM DESC),'31') AS JUN_MAGAM_DAY
    ,ISNULL((SELECT TOP 1 MAGAM_DAY FROM CM_M_CUST_MAGAM WHERE CUST_CODE=A.CUST_CODE AND APPLY_YYMM<='2607' ORDER BY APPLY_YYMM DESC),'31') AS MAGAM_DAY
  FROM CM_M_CUST A )
SELECT T.CUST_CODE, MAX(T.CUST_DESC) cust_desc, T.CUST_TYPE, T.MAT_CODE, T.MAINT_COST,
  SUM(T.MAINT_QTY) MAINT_QTY, SUM(T.MAINT_AMT) MAINT_AMT, SUM(T.MAINT_VAT) MAINT_VAT,
  T.KRW_MAINT_COST, SUM(T.KRW_MAINT_AMT) KRW_MAINT_AMT, SUM(T.KRW_MAINT_VAT) KRW_MAINT_VAT,
  MAX(T.ITEM_DESC) item_desc, MAX(T.ITEM_SPEC) item_spec, MAX(T.UNIT) unit,
  T.ITEM_LGROUP, T.ITEM_SGROUP, T.EXCHANGE_RATE,
  (SELECT CUST_DESC FROM CM_M_CUST WHERE CUST_CODE=MAX(T.IN_CUST_CODE)) in_cust, T.CURRENCY,
  isnull(MAX(T.ITEM_WEIGHT),0) item_weight
FROM (
  SELECT A.CUST_CODE, MAX(C2.CUST_DESC) CUST_DESC, C2.CUST_TYPE, A.MAT_CODE, A.MAINT_COST, A.MAINT_COST KRW_MAINT_COST,
    A.MAINT_TAG, A.GAGONG_PROC_CODE, A.ITEM_CODE, MAX(M.ITEM_DESC) ITEM_DESC, MAX(M.ITEM_SPEC) ITEM_SPEC, MAX(M.UNIT) UNIT,
    M.ITEM_LGROUP, M.ITEM_SGROUP, SUM(-A.MAINT_QTY) MAINT_QTY, SUM(-A.MAINT_AMT) MAINT_AMT, SUM(-A.MAINT_AMT) KRW_MAINT_AMT,
    SUM(-A.MAINT_VAT) MAINT_VAT, SUM(-A.MAINT_VAT) KRW_MAINT_VAT, 1 exchange_rate, MAX(M.IN_CUST_CODE) in_cust_code, 'KRW' currency, MAX(M.ITEM_WEIGHT) item_weight
   FROM PU_T_STOCK_MAINT A JOIN PR_M_ITEM M ON A.MAT_CODE=M.ITEM_CODE JOIN CM_M_CUST C2 ON A.CUST_CODE=C2.CUST_CODE
    join MAGAM mg on a.cust_code=mg.cust_code
   WHERE A.MAINT_YMD>mg.jun_yymm+mg.jun_magam_day AND A.MAINT_YMD<='2607'+mg.magam_day AND A.MAINT_TAG IN ('5')
   GROUP BY A.CUST_CODE,A.MAINT_TAG,A.GAGONG_PROC_CODE,A.MAT_CODE,A.ITEM_CODE,C2.CUST_TYPE,A.MAINT_COST,M.ITEM_LGROUP,M.ITEM_SGROUP
  UNION ALL
  SELECT A.CUST_CODE, MAX(C2.CUST_DESC), C2.CUST_TYPE, A.ITEM_CODE MAT_CODE, A.MAINT_COST, A.MAINT_COST, A.MAINT_TAG, '' , '' ,
    MAX(M.ITEM_DESC), MAX(M.ITEM_SPEC), MAX(M.UNIT), M.ITEM_LGROUP, M.ITEM_SGROUP, SUM(-A.MAINT_QTY), SUM(-A.MAINT_AMT), SUM(-A.MAINT_AMT),
    SUM(-A.MAINT_VAT), SUM(-A.MAINT_VAT), 1, MAX(M.IN_CUST_CODE), 'KRW', MAX(M.ITEM_WEIGHT)
   FROM SA_T_STOCK_MAINT A JOIN PR_M_ITEM M ON A.ITEM_CODE=M.ITEM_CODE JOIN CM_M_CUST C2 ON A.CUST_CODE=C2.CUST_CODE
    join MAGAM mg on a.cust_code=mg.cust_code
   WHERE A.MAINT_YMD>mg.jun_yymm+mg.jun_magam_day AND A.MAINT_YMD<='2607'+mg.magam_day AND A.MAINT_TAG IN ('R')
   GROUP BY A.CUST_CODE,A.MAINT_TAG,A.ITEM_CODE,A.MAINT_COST,C2.CUST_TYPE,M.ITEM_LGROUP,M.ITEM_SGROUP
  UNION ALL
  SELECT A.CUST_CODE, MAX(C2.CUST_DESC), C2.CUST_TYPE, A.MAT_CODE, A.MAINT_COST, (A.MAINT_COST*A.EXCHANGE_RATE), A.MAINT_TAG, '', A.ITEM_CODE,
    MAX(M.ITEM_DESC), MAX(M.ITEM_SPEC), MAX(M.UNIT), M.ITEM_LGROUP, M.ITEM_SGROUP, SUM(A.MAINT_QTY), SUM(A.MAINT_AMT), SUM(A.TAXPAYERS),
    0, 0, A.EXCHANGE_RATE, MAX(M.IN_CUST_CODE), A.CURRENCY, MAX(M.ITEM_WEIGHT)
   FROM PU_T_STOCK_MAINT_C A JOIN PR_M_ITEM M ON A.MAT_CODE=M.ITEM_CODE JOIN CM_M_CUST C2 ON A.CUST_CODE=C2.CUST_CODE
    join MAGAM mg on a.cust_code=mg.cust_code
   WHERE A.MAINT_YMD>mg.jun_yymm+mg.jun_magam_day AND A.MAINT_YMD<='2607'+mg.magam_day AND A.DIVISION='Q'
   GROUP BY A.CUST_CODE,A.MAINT_TAG,A.MAT_CODE,A.ITEM_CODE,A.MAINT_COST,C2.CUST_TYPE,A.EXCHANGE_RATE,M.ITEM_LGROUP,M.ITEM_SGROUP,A.CURRENCY
) T
WHERE CUST_TYPE LIKE '%'
GROUP BY T.CUST_CODE,T.CUST_TYPE,T.MAT_CODE,T.ITEM_LGROUP,T.ITEM_SGROUP,T.MAINT_COST,T.KRW_MAINT_COST,T.EXCHANGE_RATE,T.CURRENCY
"""
agg = live(f"SELECT COUNT(*) 건수, COUNT(DISTINCT CUST_CODE) 업체수, SUM(MAINT_QTY) 수량, SUM(MAINT_AMT) 금액, SUM(KRW_MAINT_AMT) 금액KRW FROM ({DW}) x")
print("== 자재불출집계표 마감기준 2607 합계 ==")
print(agg.to_string(index=False))
print("\n목표(ERP): 503건 / 32업체 / 수량 1,639,796.60 / 금액 1,726,764,857")
