# -*- coding: utf-8 -*-
import sys, io, warnings
warnings.filterwarnings("ignore")
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
sys.path.insert(0, r"d:\피앤씨인더스트리\100_AI_AGENT\Projects\New_ERP")
import db_client, pyodbc, pandas as pd
def live(sql):
    cs=(f"DRIVER={{SQL Server}};SERVER={db_client.DB_SERVER},{db_client.DB_PORT};"
        f"DATABASE=PARTNER_ERP;UID={db_client.DB_USER};PWD={db_client.DB_PASSWORD}")
    cn=pyodbc.connect(cs, readonly=True)
    try: return pd.read_sql(sql, cn)
    finally: cn.close()

MAGAM = """WITH MAGAM (CUST_CODE, JUN_YYMM, JUN_MAGAM_DAY, MAGAM_DAY) AS (
  SELECT CUST_CODE
    ,format(dateadd(MONTH,-1,convert(date,'2607'+'01',12)),'yyMM') jun_yymm
    ,ISNULL((SELECT TOP 1 MAGAM_DAY FROM CM_M_CUST_MAGAM WHERE CUST_CODE=A.CUST_CODE AND APPLY_YYMM<=format(dateadd(MONTH,-1,convert(date,'2607'+'01',12)),'yyMM') ORDER BY APPLY_YYMM DESC),'31') JUN_MAGAM_DAY
    ,ISNULL((SELECT TOP 1 MAGAM_DAY FROM CM_M_CUST_MAGAM WHERE CUST_CODE=A.CUST_CODE AND APPLY_YYMM<='2607' ORDER BY APPLY_YYMM DESC),'31') MAGAM_DAY
  FROM CM_M_CUST A )"""

def base(datecond):
    # datecond references A.MAINT_YMD and mg.*
    return f"""
  SELECT A.CUST_CODE, C2.CUST_TYPE, A.MAT_CODE, A.MAINT_COST, A.MAINT_COST KRW_MAINT_COST, M.ITEM_LGROUP, M.ITEM_SGROUP,
    SUM(-A.MAINT_QTY) MAINT_QTY, SUM(-A.MAINT_AMT) MAINT_AMT, SUM(-A.MAINT_AMT) KRW_MAINT_AMT, SUM(-A.MAINT_VAT) MAINT_VAT, SUM(-A.MAINT_VAT) KRW_MAINT_VAT, 1 exchange_rate, 'KRW' currency
   FROM PU_T_STOCK_MAINT A JOIN PR_M_ITEM M ON A.MAT_CODE=M.ITEM_CODE JOIN CM_M_CUST C2 ON A.CUST_CODE=C2.CUST_CODE join MAGAM mg on a.cust_code=mg.cust_code
   WHERE {datecond} AND A.MAINT_TAG IN ('5')
   GROUP BY A.CUST_CODE,A.MAINT_TAG,A.GAGONG_PROC_CODE,A.MAT_CODE,A.ITEM_CODE,C2.CUST_TYPE,A.MAINT_COST,M.ITEM_LGROUP,M.ITEM_SGROUP
  UNION ALL
  SELECT A.CUST_CODE, C2.CUST_TYPE, A.ITEM_CODE, A.MAINT_COST, A.MAINT_COST, M.ITEM_LGROUP, M.ITEM_SGROUP,
    SUM(-A.MAINT_QTY), SUM(-A.MAINT_AMT), SUM(-A.MAINT_AMT), SUM(-A.MAINT_VAT), SUM(-A.MAINT_VAT), 1, 'KRW'
   FROM SA_T_STOCK_MAINT A JOIN PR_M_ITEM M ON A.ITEM_CODE=M.ITEM_CODE JOIN CM_M_CUST C2 ON A.CUST_CODE=C2.CUST_CODE join MAGAM mg on a.cust_code=mg.cust_code
   WHERE {datecond} AND A.MAINT_TAG IN ('R')
   GROUP BY A.CUST_CODE,A.MAINT_TAG,A.ITEM_CODE,A.MAINT_COST,C2.CUST_TYPE,M.ITEM_LGROUP,M.ITEM_SGROUP
  UNION ALL
  SELECT A.CUST_CODE, C2.CUST_TYPE, A.MAT_CODE, A.MAINT_COST, (A.MAINT_COST*A.EXCHANGE_RATE), M.ITEM_LGROUP, M.ITEM_SGROUP,
    SUM(A.MAINT_QTY), SUM(A.MAINT_AMT), SUM(A.TAXPAYERS), 0, 0, A.EXCHANGE_RATE, A.CURRENCY
   FROM PU_T_STOCK_MAINT_C A JOIN PR_M_ITEM M ON A.MAT_CODE=M.ITEM_CODE JOIN CM_M_CUST C2 ON A.CUST_CODE=C2.CUST_CODE join MAGAM mg on a.cust_code=mg.cust_code
   WHERE {datecond} AND A.DIVISION='Q'
   GROUP BY A.CUST_CODE,A.MAINT_TAG,A.MAT_CODE,A.ITEM_CODE,A.MAINT_COST,C2.CUST_TYPE,A.EXCHANGE_RATE,M.ITEM_LGROUP,M.ITEM_SGROUP,A.CURRENCY"""

CLOSE = "A.MAINT_YMD > mg.jun_yymm+mg.jun_magam_day AND A.MAINT_YMD <= '2607'+mg.magam_day"
ISSUE = "A.MAINT_YMD between '260701' and '260718'"
for label, dc, tgt in (("마감기준","%s"%CLOSE,"503건/1,639,796.60/1,726,764,857"),("불출기준",ISSUE,"422건/752,431.35/1,137,942,026")):
    outer=f"""SELECT COUNT(*) 라인, COUNT(DISTINCT CUST_CODE) 업체, SUM(MAINT_QTY) 수량, SUM(MAINT_AMT) 금액
      FROM (SELECT CUST_CODE,CUST_TYPE,MAT_CODE,ITEM_LGROUP,ITEM_SGROUP,MAINT_COST,KRW_MAINT_COST,EXCHANGE_RATE,CURRENCY,
        SUM(MAINT_QTY) MAINT_QTY, SUM(MAINT_AMT) MAINT_AMT FROM ({base(dc)}) T
        GROUP BY CUST_CODE,CUST_TYPE,MAT_CODE,ITEM_LGROUP,ITEM_SGROUP,MAINT_COST,KRW_MAINT_COST,EXCHANGE_RATE,CURRENCY) x"""
    df=live(MAGAM+"\n"+outer)
    print(f"== {label} == (목표 {tgt})")
    print(df.to_string(index=False)); print()

print("== 대분류 ITEM_LGROUP 매핑 (PR005) ==")
print(live("SELECT DETAIL_CODE cd, DETAIL_DESC nm FROM CM_M_MASTER_DETAIL WHERE KIND_CODE='PR005' ORDER BY DETAIL_CODE").to_string(index=False))
print("\n== cm_m_cust 업체정보 컬럼 확인 ==")
print(live("SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='cm_m_cust' AND (COLUMN_NAME LIKE '%BUSINESS%' OR COLUMN_NAME LIKE '%PHONE%' OR COLUMN_NAME LIKE '%FAX%')").to_string(index=False))
